### ISSUE TITLE
How secure are the credentials

### ISSUE THREAD

**Issue by steveuk23** [Supergiovane/node-red-contrib-hikvision-ultimate#19]
Hi thanks for this.
How secure do you think the NVR login credentials are when saved ?
Will they be getting saved in a standard yaml config file on HA or encrypted some how?
Cheers

**Comment by Supergiovane** [comment]
Hi Steve
the login credentials are saved in the encrypted Node-Red file, using the standard way we developer use, to store sensible data in Node-Red.
In fact, if you copy the configuration node and paste it another PC or node-red instance, you'll note that the fields remain blank.
For more in depth information, please see [here](https://nodered.org/docs/user-guide/runtime/securing-node-red).
All my nodes uses the standard way Node-Red uses, to store sensible data, please see [here](https://nodered.org/docs/creating-nodes/credentials).

If you're using node-red in a critical environment, please be sure to protect the admin login screen and to apply the security best practices, as described in the first link above.

Either you're using Home Assitant with node-red, or a pure node-red installation, there are no differences, because sensible data are encrypted in the same way.

**Comment by steveuk23** [comment]
> Hi Steve
> the login credentials are saved in the encrypted Node-Red file, using the standard way we developers use, to store sensible data in Node-Red.
> In fact, if you copy the configuration node and paste it another PC or node-red instance, you'll note that the fields remain blank.
> For more in depth information, please see [here](https://nodered.org/docs/user-guide/runtime/securing-node-red).
> All my nodes uses the standard way Node-Red uses to store sensible data; please see [here](https://nodered.org/docs/creating-nodes/credentials).
> 
> If you're using node-red in a critical environment, please be sure to protect the admin login screen and to apply the security best practices, as described in the first link above.
> 
> Either you're using Home Assitant with node-red, or a pure node-red installation, there are no differences, because sensible data are encrypted in the same way.

Thanks for the reply.
That's great I didn't know node red did that, I'm still learning it.
I am right in thinking I can use your picture node to capture a still from my Hikvision camera and then link that to a call service node to use the "notify>mobile" so I receive a push notification with the still image if my contact sensor opens.

**Comment by Supergiovane** [comment]
Hi
Yes, you can. The picture node outputs the image in different way, so you can attach it to an email, for example, or to a Telegram message, etc...

**Comment by steveuk23** [comment]
Hi @Supergiovane 
i've been having network issues stopping me using these nodes.
Anyway i've fixed them now and managed to connect to the NVR with your node but i can't figure out how to send that image as part of a mobile notification when a contact sensor of mine opens.
Could you help at all
Thanks

**Comment by Supergiovane** [comment]
Hi
What notification node are you using?

**Comment by steveuk23** [comment]
Just the call service Node with notify to send to my mobile phone with the HA app.
Unless there's a better way? 
Thanks

**Comment by Supergiovane** [comment]
If you tell me the node’s name, i can check for you and suggest a way to do it.

**Comment by Supergiovane** [comment]
Is it the pushbullet node?

**Comment by steveuk23** [comment]
> Is it the pushbullet node?

Hi no It's literally just a call service node 
Domain: notify
Service: My entity name
It's the JSON data I can't work out
http://imgur.com/a/A7SZYCV

**Comment by Supergiovane** [comment]
Hmmm, i'm sorry, i don't have any clue with Home Assistant!
