### ISSUE TITLE
Installation fails: Node Red running on Synology VMM

### ISSUE THREAD

**Issue by GeorgWolter** [Supergiovane/node-red-contrib-hikvision-ultimate#3]
Logfile attached

[NodeRed.log](https://github.com/Supergiovane/node-red-contrib-hikvision-ultimate/files/5685316/NodeRed.log)

**Comment by Supergiovane** [comment]
Hi Georg
Your sinology doesn't have pyton framework installed.
Is your Sinology an x64 machine or an ARM machine?

**Comment by GeorgWolter** [comment]
Synology is a DS720+: Intel Celeron J4125, quad core, 64-bit
OK, I will check Python framework.

**Comment by Supergiovane** [comment]
You're running noder-red behind redmatic.
Running node-red behind redmatic, homeassistand etc, give everytime issues.
Please check that the user redmatic uses to run node-red, has enough privilege to install something in the system, because the automatic installation of python fails with the errror "ERR! sharp Intel Architecture 32-bit systems require manual installation of libvips >= 8.10.0"

**Comment by GeorgWolter** [comment]
OK, that's for tomorrow.

**Comment by Supergiovane** [comment]
I found this thread, related to python. 
I saw many issues with Python and redmatic. 
https://github.com/rdmtc/RedMatic/wiki/Node-Installation#nodes-mit-binärmodulen

**Comment by GeorgWolter** [comment]
My 3rd test-environment: DS-720+ with Node Red running in Docker: Installation works fine.

**Comment by Supergiovane** [comment]
Hi Georg,
V. 1.0.7 is out with a resizing module that doesn't rely on python anymore.
Please install and check if it installs correclty.

**Comment by GeorgWolter** [comment]
Good morning Giovane,
V. 1.0.7 installation on Synology VMM redmatic works fine.
Good job!
