### ISSUE TITLE
DS-KV6113-WPE1 and Mifare RFID events

### ISSUE THREAD

**Issue by MuadDibVV** [Supergiovane/node-red-contrib-hikvision-ultimate#70]
Hello,

  Thanks for your work.
I use the doorbell object to get ring event from my door station DS-KV6113-WPE1 and it works perfectly.

I now want to get event when i use a Mifare RFID card on my doorbell but I don't have anything on this objects. How can I get this event ?

Hikvision-Ultimate Version : 1.1.20

Node-Red running behind official docker

Thanks

**Comment by MuadDibVV** [comment]
I add that the Access Control Terminal object does not work "Service unreachable Error response :  Not found Retry"

**Comment by MuadDibVV** [comment]
(In the same way I don't know how to retrieve camera movement events on this device)

**Comment by Supergiovane** [comment]
Hi
the ISAPI protocol on the doorbell/entrance devices are barely developed. Many functionalities are missing. It has been a problem for many years and nothing has improved.
I suggest to try Home Assistant. An user has made an add-on using the Hikvision SDK instead of ISAPI (SDK isn't doable in node.js). I also use Home Assistant to hangup a doorbell call using that add-on. Search the Home Assistant forum for further help, as i can do nothing to help you.
